version: '3'
services:
  mysql_5_7:
    image: mysql:5.7
    # @see https://github.com/docker-library/docs/issues/613#issuecomment-228842790
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "13306:3306"
    volumes:
      - mysql_5_7-data:/var/lib/mysql
volumes:
  mysql_5_7-data:
